db:
  database: auth_microservice_production
  url: <%= ENV.fetch('AUTH_DATABASE_URL')%>

rabbit_mq:
  consumer_pool: 10
  host: <%= ENV.fetch('RABBITMQ_HOST')%>
  username: <%= ENV.fetch('RABBITMQ_USER')%>
  password: <%= ENV.fetch('RABBITMQ_PASSWORD')%>
